apiVersion: v1
kind: Service
# https://kubernetes.io/docs/concepts/services-networking/service/#externalname
metadata:
  name: my-service
  namespace: prod
spec:
  type: ExternalName
  externalName: my.database.example.com