apiVersion: v1
kind: Service
metadata:
  name: loadbalance-svc
  namespace: namespace
  labels:
    app: guestbook
  annotations: {}
spec:
  type: LoadBalancer
  selector:
    app: guestbook
  ports:
    - name: http
      protocol: TCP
      port: 80  # Port to access service
      targetPort: 8080  # Port in the pod
